### ISSUE TITLE
Problem with mix.copy()  and setPublicPath?

### ISSUE THREAD

**Issue by roddypratt** [laravel-mix/laravel-mix#2857]
-   Laravel Mix Version: 6.0.11
-   OS: Windows

### Description:
`mix.copy()` seems to have problems if combined with `setPublicPath`. 

### Steps To Reproduce:
```
mix.setPublicPath('output')
    .clean()
    .version()
    .ts('resources/mydir/index.ts', 'js')
    .copy('resources/mydir/index.html', 'html')
```

**Expected:** Creates output/js/index.js and output/html/index.html
**Actual:** 
Creates output/js/index.js and html/index.html, then fails:-

```
> UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'C:\Rascular\output\html\index.html'
>     at Object.openSync (fs.js:466:3)
>     at Object.readFileSync (fs.js:369:35)
>     at File.read (C:\Rascular\node_modules\laravel-mix\src\File.js:218:19)
>     at File.version (C:\Rascular\node_modules\laravel-mix\src\File.js:225:25)
>     at Manifest.hash (C:\Rascular\node_modules\laravel-mix\src\Manifest.js:51:65)
>     at C:\Rascular\node_modules\laravel-mix\src\webpackPlugins\CustomTasksPlugin.js:110:71
>     at Collection.each (C:\Rascular\node_modules\collect.js\dist\methods\each.js:21:14)
>     at CustomTasksPlugin.applyVersioning (C:\Rascular\node_modules\laravel-mix\src\webpackPlugins\CustomTasksPlugin.js:110:37)
>     at C:\Rascular\node_modules\laravel-mix\src\webpackPlugins\CustomTasksPlugin.js:14:26
>     at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

 To fix, I must use
`.copy('resources/mydir/index.html', 'output/html')`
I

**Comment by saas786** [comment]
Same is true with `mix.combine()`

By default its fine, as we expect output files to show up in `public` path, but in some situations, when we want to `copy / combine `into different output path, it throws error.

**Comment by cakleimeier** [comment]
I'm running into the same issue with using `setPublicPath` and `copyDirectory`. Has there been any movement on this issue?

**Comment by pdsuk** [comment]
Same problem here with copy and copyDirectory

**Comment by jwoertink** [comment]
Same with version `6.0.39` on macOS. It seems with `copy` and `copyDirectory`, you have to prepend your publicPath

```javascript
mix
  .setPublicPath("public")
  .js("src/js/app.js", "js") // copy to public/js
  .sass("src/css/app.scss", "css") // copy to public/css
  .copy("src/images/*", "public/images") // copy to public/images
```
