### ISSUE TITLE
Using config "imgLoaderOptions" fails with "Invalid host defined options"

### ISSUE THREAD

**Issue by ftbastler** [laravel-mix/laravel-mix#3111]
-   Laravel Mix Version: 6.0.31
-   Node Version: v16.8.0
-   NPM Version: 7.24.1
-   OS: macOS

### Description:

```
ERROR in ./resources/assets/sass/style.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/img-loader/index.js):
TypeError: Invalid host defined options
    at Object.module.exports (./node_modules/img-loader/index.js:14:3)
    at processResult (./node_modules/webpack/lib/NormalModule.js:721:19)
    at ./node_modules/webpack/lib/NormalModule.js:827:5
    at ./node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at ./node_modules/loader-runner/lib/LoaderRunner.js:251:18
    at context.callback (./node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at ./node_modules/img-loader/index.js:19:31
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

#### webpack.mix.js
```
  mix.options({
    imgLoaderOptions: {
      plugins: [
        require('imagemin-gifsicle')({
          interlaced: false
        }),
        require('imagemin-mozjpeg')({
          progressive: true,
          arithmetic: false
        }),
        require('imagemin-pngquant')({
          floyd: 0.5,
          speed: 2,
          quality: [0.6, 0.8]
        })
      ]
    }
   });
```

#### package.json
```
    "devDependencies": {
        "imagemin": "^7.0.1",
        "imagemin-gifsicle": "^7.0.0",
        "imagemin-mozjpeg": "^9.0.0",
        "imagemin-pngquant": "^9.0.2",
        "laravel-mix": "^6.0.31",
        "laravel-mix-polyfill": "^3.0.1",
        "resolve-url-loader": "^4.0.0",
        "sass": "^1.42.1",
        "sass-loader": "^12.1.0",
        "vue-loader": "^15.9.8",
        "webpack": "^5.54.0"
        // ...
    },
```

Maybe related to https://github.com/danielstgt/laravel-mix-svg-vue/issues/8 ?

**Comment by thecrypticace** [comment]
The ESM import shouldn't be an issue because it's a dynamic import. However webpack CLI does weird stuff with dynamic ESM imports. I'll make a note to add integration tests for this and figure out a fix for Mix v6.1. I'm planning to add ESM mix config file support there as well.

**Comment by ftbastler** [comment]
Any short-term fix I could apply?

**Comment by thecrypticace** [comment]
At the moment the only thing I can think of is using yarn + resolutions to fix the imagemin version at 3.0 instead of 4.0. Otherwise, I'm not sure.

**Comment by thecrypticace** [comment]
You can maybe try using this:
```
DISABLE_V8_COMPILE_CACHE=1 npm run dev
``

(or yarn / pnpm / etc…)
