### ISSUE TITLE
6.0.35+ no longer works with Node 14 due to "Digest method not supported"

### ISSUE THREAD

**Issue by smares** [laravel-mix/laravel-mix#3168]
-   Laravel Mix Version: 6.0.35 (`npm list --depth=0`)
-   Node Version (`node -v`): 14.18.1
-   NPM Version (`npm -v`): 6.14.15
-   OS: node14-alpine

### Description:

Starting with 6.0.35, running `npm run dev` outputs "Digest method not supported". 6.0.34 still works fine.

**Comment by thecrypticace** [comment]
Try running yarn upgrade or npm upgrade

**Comment by smares** [comment]
Didn't change anything - it didn't even update anything.

**Comment by thecrypticace** [comment]
It says above that you're running v6.0.35 but the latest version of Mix is 6.0.39 which should not have this problem. We had a series of releases related to handling some Node 17 breaks and had to make tweaks for earlier node versions as well.

**Comment by smares** [comment]
6.0.39 also has the same problem. That is why I said 6.0.35+. 6.0.34 is the last working version.

**Comment by smares** [comment]
This is the complete output of the error with 6.0.39:

```
(node:35) UnhandledPromiseRejectionWarning: Error: Digest method not supported
    at new Hash (internal/crypto/hash.js:46:19)
    at Object.createHash (crypto.js:116:10)
    at BulkUpdateDecorator.hashFactory (/app/node_modules/webpack/lib/util/createHash.js:145:18)
    at BulkUpdateDecorator.update (/app/node_modules/webpack/lib/util/createHash.js:46:50)
    at SourceMapSource.updateHash (/app/node_modules/webpack/node_modules/webpack-sources/lib/SourceMapSource.js:233:8)
    at NormalModule._initBuildHash (/app/node_modules/webpack/lib/NormalModule.js:868:17)
    at handleParseResult (/app/node_modules/webpack/lib/NormalModule.js:934:10)
    at /app/node_modules/webpack/lib/NormalModule.js:1026:4
    at processResult (/app/node_modules/webpack/lib/NormalModule.js:743:11)
    at /app/node_modules/webpack/lib/NormalModule.js:807:5
(Use `node --trace-warnings ...` to show where the warning was created)
(node:35) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:35) UnhandledPromiseRejectionWarning: Error: Digest method not supported
    at new Hash (internal/crypto/hash.js:46:19)
    at Object.createHash (crypto.js:116:10)
    at BulkUpdateDecorator.hashFactory (/app/node_modules/webpack/lib/util/createHash.js:145:18)
    at BulkUpdateDecorator.update (/app/node_modules/webpack/lib/util/createHash.js:46:50)
    at OriginalSource.updateHash (/app/node_modules/webpack/node_modules/webpack-sources/lib/OriginalSource.js:104:8)
    at NormalModule._initBuildHash (/app/node_modules/webpack/lib/NormalModule.js:868:17)
    at handleParseResult (/app/node_modules/webpack/lib/NormalModule.js:934:10)
    at /app/node_modules/webpack/lib/NormalModule.js:1026:4
    at processResult (/app/node_modules/webpack/lib/NormalModule.js:743:11)
    at /app/node_modules/webpack/lib/NormalModule.js:807:5
(node:35) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

**Comment by smares** [comment]
Problem solved, sorry. Installed the missing peer dependencies manually and the build works now. :)

**Comment by thecrypticace** [comment]
Yeah with the way Mix runs things webpack is _technically_ supposed to be a peer dependency even though it includes it itself. This was added because otherwise neither of Yarn PnP nor pnpm work.

I'm hoping we can resolve this by having the option of not running webpack-cli and having Mix run webpack directly. I'm not certain though how this will play out.
