### ISSUE TITLE
Error when using `mix watch` with Vue 3 and TypeScript

### ISSUE THREAD

**Issue by binotaliu** [laravel-mix/laravel-mix#3184]
-   Laravel Mix Version: 6.0.39
-   Node Version: 17.2.0
-   NPM Version: 8.1.4
-   OS: macOS 12.1

```
vue-ts-watch@0.1.0
├── @vue/compiler-sfc@3.2.26
├── laravel-mix@6.0.39
├── ts-loader@9.2.6
├── typescript@4.5.4
├── vue-loader@16.8.3
└── vue@3.2.26
```

### Description:

This is a very weird bug, it only happen when you using `mix watch` and made some changes to file to triggering recompilation. Even if you changed nothing semantically (like adding a space or new line).

Error message looks like this:
```
● Mix █████████████████████████  (0%)  
 

[@vue/compiler-sfc] compileTemplate now requires the `id` option.`.

[webpack-cli] Error: The loaded module contains errors
    at /Users/binota/Developer/vue-ts-watch/node_modules/webpack/lib/dependencies/LoaderPlugin.js:108:11
    at /Users/binota/Developer/vue-ts-watch/node_modules/webpack/lib/Compilation.js:1930:5
    at /Users/binota/Developer/vue-ts-watch/node_modules/webpack/lib/util/AsyncQueue.js:352:5
    at Hook.eval [as callAsync] (eval at create (/Users/binota/Developer/vue-ts-watch/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncQueue._handleResult (/Users/binota/Developer/vue-ts-watch/node_modules/webpack/lib/util/AsyncQueue.js:322:21)
    at /Users/binota/Developer/vue-ts-watch/node_modules/webpack/lib/util/AsyncQueue.js:305:11
    at /Users/binota/Developer/vue-ts-watch/node_modules/webpack/lib/Compilation.js:1392:15
    at /Users/binota/Developer/vue-ts-watch/node_modules/webpack/lib/HookWebpackError.js:68:3
    at Hook.eval [as callAsync] (eval at create (/Users/binota/Developer/vue-ts-watch/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at Cache.store (/Users/binota/Developer/vue-ts-watch/node_modules/webpack/lib/Cache.js:107:20)
```

It didn't give us anything useful, so I dig up into `node_modules/webpack/lib/dependencies/LoaderPlugin.js` and print the actual "loaded module" errors out:
```diff
107d106
>                   console.error(referencedModule)
```

We can see errors now:
```
    ModuleError: Module Error (from ./node_modules/vue-loader/dist/index.js):
    
    VueCompilerError: Element is missing end tag.
    at /Users/binota/Developer/vue-ts-watch/src/utils.ts:1:21
    1  |  export const clone: <T>(v: T) => T = (v) => JSON.parse(JSON.stringify(v))
       |                      ^
    2  |  
    3  |  
    
        at Object.emitError (/Users/binota/Developer/vue-ts-watch/node_modules/webpack/lib/NormalModule.js:601:6)
        at /Users/binota/Developer/vue-ts-watch/node_modules/vue-loader/dist/index.js:51:27
        at Array.forEach (<anonymous>)
        at Object.loader (/Users/binota/Developer/vue-ts-watch/node_modules/vue-loader/dist/index.js:49:16)
        at LOADER_EXECUTION (/Users/binota/Developer/vue-ts-watch/node_modules/loader-runner/lib/LoaderRunner.js:132:14)
        at runSyncOrAsync (/Users/binota/Developer/vue-ts-watch/node_modules/loader-runner/lib/LoaderRunner.js:133:4)
        at iterateNormalLoaders (/Users/binota/Developer/vue-ts-watch/node_modules/loader-runner/lib/LoaderRunner.js:250:2)
        at /Users/binota/Developer/vue-ts-watch/node_modules/loader-runner/lib/LoaderRunner.js:223:4
        at /Users/binota/Developer/vue-ts-watch/node_modules/webpack/lib/NormalModule.js:827:15
        at eval (eval at create (/Users/binota/Developer/vue-ts-watch/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:12:1)
    SyntaxError: 
    VueCompilerError: Element is missing end tag.
    at /Users/binota/Developer/vue-ts-watch/src/utils.ts:1:21
    1  |  export const clone: <T>(v: T) => T = (v) => JSON.parse(JSON.stringify(v))
       |                      ^
    2  |  
    3  |  
    
        at createCompilerError (/Users/binota/Developer/vue-ts-watch/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:19:19)
        at emitError (/Users/binota/Developer/vue-ts-watch/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:1594:29)
        at parseElement (/Users/binota/Developer/vue-ts-watch/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:1146:9)
        at parseChildren (/Users/binota/Developer/vue-ts-watch/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:937:28)
        at Object.baseParse (/Users/binota/Developer/vue-ts-watch/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:852:23)
        at Object.parse (/Users/binota/Developer/vue-ts-watch/node_modules/@vue/compiler-dom/dist/compiler-dom.cjs.js:3077:25)
        at Object.parse (/Users/binota/Developer/vue-ts-watch/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:4768:26)
        at Object.loader (/Users/binota/Developer/vue-ts-watch/node_modules/vue-loader/dist/index.js:39:56)
```

Some how, when webpack recompile the file, it just decided to use vue-loader for `*.ts` files?
I really have no idea why this happen. And it confused me why it was compiled successfully for the first time.

### Steps To Reproduce:

1. Clone the reproduce repo here: [binotaliu/vue-ts-watch](/binotaliu/vue-ts-watch)
2. Run `npm ci`
3. Run `npx mix watch`
4. Open `src/App.vue` with text editor and make some changes. (For example, add a new empty line)

**Comment by binotaliu** [comment]
I found the solution is to **use TypeScript file for your entry file.** 

References:
https://github.com/symfony/webpack-encore/issues/1013
https://stackoverflow.com/a/68875755
