### ISSUE TITLE
 Error: [BABEL] unknown: Preset /* your preset */ requires a filename to be set when babel is called directly,

### ISSUE THREAD

**Issue by joelharkes** [laravel-mix/laravel-mix#3219]
-   Laravel Mix Version: @6.0.42 (`npm list --depth=0`)
-   Node Version (`node -v`): `v17.4.0`
-   NPM Version (`npm -v`): `8.3.1`
-   OS: macOS

### Description:

getting the following error when running Babel (+react+ typescript):

```
 Error: [BABEL] unknown: Preset /* your preset */ requires a filename to be set when babel is called directly,
```
babel.transform(code, { filename: 'file.ts', presets: [/* your preset */] });
```
See https://babeljs.io/docs/en/options#filename for more information.
    at validateIfOptionNeedsFilename (/Users/xxx/mobilityshop-api/node_modules/@babel/core/lib/config/full.js:331:11)
    at /Users/xxx/mobilityshop-api/node_modules/@babel/core/lib/config/full.js:343:52
    at Array.forEach (<anonymous>)
....
```

I cant seem to fix it, I googled all the options but none worked.

### Steps To Reproduce:

webpack.mix.js
```js
let mix = require('laravel-mix');
const fs = require("fs");

fs.readdirSync("./resources/ts/bundles/", "utf8")
    .filter(x => x.match(/\.tsx?$/g))
    .forEach(x => {
        mix.babel(`./resources/ts/bundles/${x}`,`public/${x.replace('.tsx','.js', true)}`).setPublicPath('public');
    });
```

babel.config.js:
```js
module.exports = {
    presets: [
        ["@babel/preset-env",
            {
                "useBuiltIns": "usage",
                "corejs": 3
            }],
        "@babel/preset-typescript",
        ["@babel/preset-react", {
            "runtime": "automatic"
        }],
    ],
    "plugins": [
        "@babel/proposal-class-properties",
        "@babel/proposal-object-rest-spread"
    ],
};

```

using `mix.ts()` works but it would bring our build time to 2 minutes so we'd rather avoid that.

**Comment by joelharkes** [comment]
adding webpack config explicitly doesnt seem to fix anything:
```js
mix.webpackConfig({
    devServer: {
        port: '8101',
        host: "0.0.0.0",
        allowedHosts: 'all',
        headers: {
            "Access-Control-Allow-Origin": "*",
        },
    },
    resolve: {
        symlinks: false,
    },
    output: {
        path: path.resolve(__dirname, "public"),
        filename: "[name].js",
    }
})
```

**Comment by xDemonRU** [comment]
I have the same problem. Still no solution?
