### ISSUE TITLE
laravel-mix 6.0.47 with VueJs (Vue 2): [webpack-cli] TypeError: Cannot read property 'includes' of undefined

### ISSUE THREAD

**Issue by NeurohrByteS** [laravel-mix/laravel-mix#3274]
-   Laravel Mix Version: 6.0.47 (`npm list --depth=0`)
-   Node Version (`node -v`): v14.19.1
-   NPM Version (`npm -v`): 8.11.0
-   OS: Debian GNU/Linux 10 (buster)

### Description:

When trying either `npm run prod` or `npm run dev`
```
[webpack-cli] TypeError: Cannot read property 'includes' of undefined
    at Vue.webpackConfig (/path_to_project/laravel/node_modules/laravel-mix/src/components/Vue.js:110:39)
    at /path_to_project/laravel/node_modules/laravel-mix/src/components/ComponentRegistrar.js:124:54
    at /path_to_project/laravel/node_modules/laravel-mix/src/Dispatcher.js:39:62
    at Array.map (<anonymous>)
    at Dispatcher.fire (/path_to_project/laravel/node_modules/laravel-mix/src/Dispatcher.js:39:47)
    at Mix.dispatch (/path_to_project/laravel/node_modules/laravel-mix/src/Mix.js:248:32)
    at WebpackConfig.build (/path_to_project/laravel/node_modules/laravel-mix/src/builder/WebpackConfig.js:37:24)
    at async loadConfigByPath (/path_to_project/laravel/node_modules/webpack-cli/lib/webpack-cli.js:1747:21)
    at async Promise.all (index 0)
    at async WebpackCLI.loadConfig (/path_to_project/laravel/node_modules/webpack-cli/lib/webpack-cli.js:1765:29)
    at async WebpackCLI.createCompiler (/path_to_project/laravel/node_modules/webpack-cli/lib/webpack-cli.js:2187:18)
    at async WebpackCLI.runWebpack (/path_to_project/laravel/node_modules/webpack-cli/lib/webpack-cli.js:2323:16)
    at async Command.<anonymous> (/path_to_project/laravel/node_modules/webpack-cli/lib/webpack-cli.js:1060:13)
    at async Promise.all (index 1)
    at async Command.<anonymous> (/path_to_project/laravel/node_modules/webpack-cli/lib/webpack-cli.js:1674:7)
```
WebPack attached:
[webpack.mix.js.txt](https://github.com/laravel-mix/laravel-mix/files/8837561/webpack.mix.js.txt)

Package.json attached:
[package.json.txt](https://github.com/laravel-mix/laravel-mix/files/8837562/package.json.txt)

~~Forcing the old version `npm install laravel-mix@6.0.43` (based on my `npm-shrinkwrap.json` this was the previous version) works to make the project compilable again.~~
**Edit**: The joys of caching... actually it's reverting back to `npm install laravel-mix@6.0.42`, see below.

### Steps To Reproduce:

Have a project with above setup and try to compile.

**Comment by NeurohrByteS** [comment]
Is there any way to get which include fails? I could also provide both `npm-shrinkwrap.json` but as expected there are hundreds of seemingly minor updates.

**Comment by NeurohrByteS** [comment]
Changing [components/Vue.js#L110](https://github.com/laravel-mix/laravel-mix/blob/master/src/components/Vue.js#L110) from
```js
if (loader.loader.includes('file-loader')) {
```

to

```
if (loader.loader && loader.loader.includes('file-loader')) {
```

Solves the symptom and makes it compilable again.

I don't think that this is an actual solution, but since file-loader doesn't seem to have any recent updates I'm out of ideas.

**Comment by NeurohrByteS** [comment]
@thecrypticace

Changing [components/Vue.js#L110](https://github.com/laravel-mix/laravel-mix/blob/master/src/components/Vue.js#L110) from
```js
if (loader.loader.includes('file-loader')) {
```

to

```js
if (loader.loader && loader.loader.includes('file-loader')) {
```

solves the symptom and makes it compilable again.

I don't think that this is an actual solution, but it would have worked for the projects where I made that change.

The change in [Vue.js is only 15 days old](https://github.com/laravel-mix/laravel-mix/commit/93ed3c159fd2f97b2ed0b4275c72c95780ac765c), hence I'm currently testing `npm install laravel-mix@6.0.42` everywhere.
 
**Edit: laravel-mix@6.0.42 works.**

**Comment by thecrypticace** [comment]
🤦 pushing a release out in 5m once the tests pass on everything

**Comment by thecrypticace** [comment]
Fixed in https://github.com/laravel-mix/laravel-mix/commit/17a3964a10781d4cecf307d18efd152e780d88e0

v6.0.48 has been published
